// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jijuegdzijgrrquvigdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppanVlZ2R6aWpncnJxdXZpZ2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MTc1NzMsImV4cCI6MjA4ODI5MzU3M30.07JLLdurTn30JMNIUKaKOakznGaL3W5xYZFe9NqS02A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});